### ISSUE TITLE
flex vs box

### ISSUE THREAD

**Issue by SKing7** [SKing7/sking7.github.com#16]
在UC调试flex的问题时发现，uc对flex标准的支持不好；
兼容性的写法是：
```css
.wrapper { 
 display: -webkit-box;
 display: -webkit-flex; 
 display: flex; 
}
```
align-item的对应写法：
```css
{
-webkit-align-items: center;
-webkit-box-align:center;
align-items: center; 
}
```
flex: 1 对应写法：
```css
-webkit-box-flex:1
-webkit-flex: 1;
flex:1;
```
以此类推：
参考：
- http://stackoverflow.com/questions/16280040/css3-flexbox-display-box-vs-flexbox-vs-flex
- https://www.w3.org/TR/2009/WD-css3-flexbox-20090723/
