### ISSUE TITLE
三角形的分割错觉

### ISSUE THREAD

**Issue by SKing7** [SKing7/sking7.github.com#36]
先看一个效果：
![image](https://user-images.githubusercontent.com/1629189/39864784-5c8b3428-547d-11e8-82f5-a9430e9faceb.png)
这是使用css实现的播放按钮，感官上感觉三角形的位置不是居中的。
但是通过看代码实现，发现其实三角形就是居中的：
```css
.wrapper {
  margin: 0 auto;
  display: flex;
  align-items: center;
  justify-content: center;
}
```
但是为什么感觉上总是觉得偏左呢？

## 三角形分割错觉

先回顾下三角形的质心：

> 三角形质心是基于最小外接矩形的。所以，如果你打算把一个点放到等边三角形高度一半的位置，你会> 发现它看起来要超过一半。

质心就是一个物体的质量集中于此的一个假想点；
根据结论：三角形的质心是三条中位线的交点（可[参考](https://www.physixfan.com/%E8%AF%81%E6%98%8E%EF%BC%9A%E4%B8%89%E8%A7%92%E5%BD%A2%E7%9A%84%E8%B4%A8%E5%BF%83%E6%98%AF%E4%B8%89%E6%9D%A1%E4%B8%AD%E7%BA%BF%E4%BA%A4%E7%82%B9/)）。

这里我们用的等边三角形，等边三角形腰的中点与对角顶点连线的交点，来找出三角形的质点。
质点的坐标公式：
![image](https://user-images.githubusercontent.com/1629189/39865287-f2c80f1e-547e-11e8-96df-afd347c98ab5.png)。
也就是说，质点在三角形中心的下面，当你把三角形放在中心的位置时，质心是偏左的，也就感觉到三角形位置偏左。
