### ISSUE TITLE
iPhone X开发规范

### ISSUE THREAD

**Issue by SKing7** [SKing7/sking7.github.com#38]
在之前的移动设备适配的时候，iPhoneX的尺寸和“造型”比较特殊。所以iPhone X在顶部和底部传感器区域都要考虑下适配。
![image](https://user-images.githubusercontent.com/1629189/40700227-4324b098-640b-11e8-9b43-3c6319084f89.png)

# 全屏
iOS 11引入了新的meta Tag：`viewport-fit`
默认值是`auto`, 自动适应`safe area`
可以设置值为`cover`，可以让内容全屏。
> <meta name='viewport' content='initial-scale=1, viewport-fit=cover'>

# Safe Area
![image](https://user-images.githubusercontent.com/1629189/40700719-4fc5e2d4-640d-11e8-8058-d3fd62640fa7.png)

iOS中考虑Safe Area，同时引入了4个环境变量：
`safe-area-inset-left, safe-area-inset-right, safe-area-inset-top, and safe-area-inset-bottom`

```css
.post {
    padding: 12px;
    padding-left: env(safe-area-inset-left);
    padding-right: env(safe-area-inset-right);
}
```

# 参考
- https://webkit.org/blog/7929/designing-websites-for-iphone-x/
- https://www.paintcodeapp.com/news/iphone-x-screen-demystified
- https://developer.apple.com/ios/human-interface-guidelines/overview/iphone-x/
- https://www.paintcodeapp.com/news/ultimate-guide-to-iphone-resolutions
